### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [romgere/romgere_cockpit#1]
In the file "romgere_cockpit/lib/Misc/MasterToSlaveCommand.cpp" the `Wire.requestFrom()` is followed by a `Wire.endTransmission()`. That `Wire.endTransmission()` may be removed. It is at the moment at line 99.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by romgere** [comment]
@Koepel thank for the issue and the link. I juste starting again to work on this library, last time I used it the Wire communication between 2 boards was not working... Perhaps because of this ? Anyway this had to be fixed :)

Do you know if I need to delete all `Wire.endTransmission()` calls or is it needed after the `Wire.write()` on line 79 ?

**Comment by Koepel** [comment]
The Wire.beginTransmission() clears variables and clears a buffer (inside the Wire library).
The Wire.write() writes data to that buffer.
The Wire.endTransmission() does the full I2C bus transaction and uses data from that buffer.

So the **Wire.endTransmission() does all the work**, but it is only used when writing data.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).
